secrets:
    gmail:
        from: ENC[AES256_GCM,data:ZzPp0sEEP0y2MHKqJFID5GRH1b0Fiof2,iv:khR8RXSKIf6K0k2dvCh/ukUT5TeAATnKhehfokfy0kY=,tag:xqA2G3UD1bRpAiYyR1Wxxw==,type:str]
        to: ENC[AES256_GCM,data:veukfbPiYiQ+goK95mfSykgPuZ3zy++K,iv:S4AXBSY4p1InHtoDIafjnQCPTNrBnDnglXlUFRwxI7Q=,tag:8sdptczTxeJMOmpq77Ry0A==,type:str]
        appPassword: ENC[AES256_GCM,data:wuSp/z+2jeANenbR/UQDXIS0hg==,iv:hDHor9ypKPkfDnhJN7rEAFrAZYTXgOrfTO91E+xUGZs=,tag:O6W2wILS8siOX1xoaqIc/w==,type:str]
    ngrok:
        authToken: ENC[AES256_GCM,data:7bJwwSKV/r9MSu12AXnDc4j+5deXN5XggT6lRsLNmo3hTVI40g0lv+2d9v50BPm3mA==,iv:oNHBDIlWwX9+owiJipzHUIeQx/e+KYpQRblBvx1VAXM=,tag:llUPJu4nI+CE09dE3SqO3Q==,type:str]
sops:
    age:
        - recipient: age10jftd4a6z00h37trzsvrst5nsqu477tx67yfxqdhf07gj233tu3q6peps3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSQkJSTFdqWHVzNkRVb0dl
            Z3U1QlhwbEhKRjBjNUIwYnc5M1BBYnByczBrCk1lNFpqbklGWG5lSnBTdS9xa1M1
            dUdEd3h0K1pmOTlKM1Q4Sld5SGtVME0KLS0tIG1JdGloYTNZWnJReFA4QlR6L3pC
            WlAvbTI1bzFpS2szeml6bFZDUjAyQ1UK9oZ1td30JZV5mPK/ZFCOUtT8zYa7y5X0
            u1EVmvsiDjJFAWQOBQT7uWftHFKHFQdi0GKPyYlme09QMta9F3vhDQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-13T08:39:26Z"
    mac: ENC[AES256_GCM,data:FIyYQb4GGUZi7YXI33Zrlr5vm4/umGHe3N2G3eVk24zxVnIRAIeLg+ROHEUv8iYvBr3A5ToLi0+lPm+1HXiQhFVaI3i1sGyGr014vPCx+1v4QTbhPQtNqk2xkrQOBX3kjkQPEaFL0X5lRDo7kvXUjhL6aOGnwernBum/SGC9Rpc=,iv:+dID1nwlgx0xd4taLSjHHecg1wrfV81fbSS5yIJnTpE=,tag:qOJMP5qtIMsm+ZqLE7hxHg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
