{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "crashloop-stack.fullname" . }}-reader
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get","list","watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "crashloop-stack.fullname" . }}-reader-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "crashloop-stack.fullname" . }}-reader
subjects:
  - kind: ServiceAccount
    name: {{ include "crashloop-stack.fullname" . }}-sa
    namespace: {{ .Values.namespace }}
{{- end }}
