{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.name }}
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  ALERT_EMAIL_FROM: {{ .Values.secrets.gmail.from | quote }}
  ALERT_EMAIL_TO: {{ .Values.secrets.gmail.to | quote }}
  GMAIL_APP_PASSWORD: {{ .Values.secrets.gmail.appPassword | quote }}
  NGROK_AUTHTOKEN: {{ .Values.secrets.ngrok.authToken | quote }}
{{- end }}
