apiVersion: v1
kind: Pod
metadata:
  name: crashloop-test
  labels:
    app: crashloop-test
spec:
  restartPolicy: Always
  containers:
  - name: crash
    image: busybox:1.36
    command: ["sh","-c","echo 'crashing now...' && sleep 2 && exit 1"]